# Generated by Django 5.1.1 on 2024-10-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mobilecompany_mobile_mobilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(default='media/4.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image1',
            field=models.ImageField(default='media/4.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image2',
            field=models.ImageField(default='media/4.png', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='mobile',
            name='image3',
            field=models.ImageField(default='media/4.png', upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='MobilePicture',
        ),
    ]
